language: objective-c
os: osx
osx_image: xcode9.4
sudo: required
python: '3.7'
git:
  depth: 1
branches:
  only:
  - master

env:
  global:
  - BUILD_VERSION="0.4b0"

before_install:
- brew install python3
- python3 -m venv venv
- source venv/bin/activate
- python3 -m pip install -U pip
- python3 -m pip install py2app
- nvm install v8.9.1
- nvm use v8.9.1
- npm install -g appdmg

install:
- wget https://github.com/namuan/http-rider/archive/${BUILD_VERSION}.tar.gz -O ./httprider.tar.gz
- tar -xvf ./httprider.tar.gz
- mv http-rider-${BUILD_VERSION}/* .
- rm -rf httprider.tar.gz http-rider-${BUILD_VERSION}
- python3 -m pip install -r requirements.txt

script:
- rm -rf build
- rm -rf dist
- python3 setup.py py2app
- mv dist/HttpRider.app "${TRAVIS_BUILD_DIR}"
# - appdmg dmg.json dist/HttpRider-${BUILD_VERSION}-macOS.dmg
# - mv dist/HttpRider-${BUILD_VERSION}-macOS.dmg 
- echo "Done!"

notifications:
  email: false

before_deploy:
- git config --local user.name "namuan"
- git remote set-url origin https://namuan:${GITHUB_TOKEN}@github.com/namuan/http-rider-osx.git
- git push origin :refs/tags/${BUILD_VERSION}
- git tag -f -am v${BUILD_VERSION} ${BUILD_VERSION}

deploy:
  provider: releases
  api-key: "${GITHUB_TOKEN}"
  file: "${TRAVIS_BUILD_DIR}/HttpRider.app"
  overwrite: true
  skip_cleanup: true
  on:
    repo: namuan/http-rider-osx